api:
  name: "Inventory System API"
  version: "0.0.1"

server:
  port: 8080
  # Include message when throwing Resource Exception
  error:
    include-message: always

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  # Enable H2 Console for viewing the in-memory database
  # This is for testing and development purposes only
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  data:
    jpa:
      repositories:
        bootstrap-mode: default

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: debug
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: error
