INSERT INTO TYPE (NAME, DESCRIPTION, COST, ACTIVE, CREATED_DATE, MODIFIED_DATE) VALUES ('T-Shirt', 'T-Shirt', 6.50, 1, NOW(), null);
INSERT INTO TYPE (NAME, DESCRIPTION, COST, ACTIVE, CREATED_DATE, MODIFIED_DATE) VALUES ('Short', 'Short', 5.99, 1, NOW(), null);
INSERT INTO TYPE (NAME, DESCRIPTION, COST, ACTIVE, CREATED_DATE, MODIFIED_DATE) VALUES ('Jeans', 'Short', 25.10, 1, NOW(), null);

INSERT INTO ITEM (TYPE_ID, NAME, DESCRIPTION, COST, ITEM_COUNT, ACTIVE, CREATED_DATE, MODIFIED_DATE) VALUES ((SELECT ID FROM TYPE WHERE NAME = 'T-Shirt'), 'Blue T-Shirt (S)', 'T-Shirt', 6.50, 100, 1, NOW(), null);
INSERT INTO ITEM (TYPE_ID, NAME, DESCRIPTION, COST, ITEM_COUNT, ACTIVE, CREATED_DATE, MODIFIED_DATE) VALUES ((SELECT ID FROM TYPE WHERE NAME = 'T-Shirt'), 'Blue T-Shirt (M)', 'T-Shirt', 6.75, 240, 1, NOW(), null);
INSERT INTO ITEM (TYPE_ID, NAME, DESCRIPTION, COST, ITEM_COUNT, ACTIVE, CREATED_DATE, MODIFIED_DATE) VALUES ((SELECT ID FROM TYPE WHERE NAME = 'T-Shirt'), 'Blue T-Shirt (L)', 'T-Shirt', 6.90, 180, 1, NOW(), null);
INSERT INTO ITEM (TYPE_ID, NAME, DESCRIPTION, COST, ITEM_COUNT, ACTIVE, CREATED_DATE, MODIFIED_DATE) VALUES ((SELECT ID FROM TYPE WHERE NAME = 'T-Shirt'), 'Green T-Shirt (S)', 'T-Shirt', 6.50, 100, 1, NOW(), null);
INSERT INTO ITEM (TYPE_ID, NAME, DESCRIPTION, COST, ITEM_COUNT, ACTIVE, CREATED_DATE, MODIFIED_DATE) VALUES ((SELECT ID FROM TYPE WHERE NAME = 'T-Shirt'), 'Green T-Shirt (M)', 'T-Shirt', 6.75, 240, 1, NOW(), null);
INSERT INTO ITEM (TYPE_ID, NAME, DESCRIPTION, COST, ITEM_COUNT, ACTIVE, CREATED_DATE, MODIFIED_DATE) VALUES ((SELECT ID FROM TYPE WHERE NAME = 'T-Shirt'), 'Green T-Shirt (L)', 'T-Shirt', 6.90, 180, 1, NOW(), null);

INSERT INTO ITEM (TYPE_ID, NAME, DESCRIPTION, COST, ITEM_COUNT, ACTIVE, CREATED_DATE, MODIFIED_DATE) VALUES ((SELECT ID FROM TYPE WHERE NAME = 'Short'), 'Black Short', 'Short', 5.99, 100, 1, NOW(), null);
INSERT INTO ITEM (TYPE_ID, NAME, DESCRIPTION, COST, ITEM_COUNT, ACTIVE, CREATED_DATE, MODIFIED_DATE) VALUES ((SELECT ID FROM TYPE WHERE NAME = 'Short'), 'Red Basketball Short', 'Basketball Short', 6.05, 80, 1, NOW(), null);
INSERT INTO ITEM (TYPE_ID, NAME, DESCRIPTION, COST, ITEM_COUNT, ACTIVE, CREATED_DATE, MODIFIED_DATE) VALUES ((SELECT ID FROM TYPE WHERE NAME = 'Short'), 'Maroon5 Short', 'Short', 6.05, 60, 1, NOW(), null);

INSERT INTO ITEM (TYPE_ID, NAME, DESCRIPTION, COST, ITEM_COUNT, ACTIVE, CREATED_DATE, MODIFIED_DATE) VALUES ((SELECT ID FROM TYPE WHERE NAME = 'Jeans'), 'Billy Jeans', 'Jeans', 25.99, 100, 1, NOW(), null);
INSERT INTO ITEM (TYPE_ID, NAME, DESCRIPTION, COST, ITEM_COUNT, ACTIVE, CREATED_DATE, MODIFIED_DATE) VALUES ((SELECT ID FROM TYPE WHERE NAME = 'Jeans'), 'Levis Jeans', 'Jeans', 26.10, 80, 1, NOW(), null);
INSERT INTO ITEM (TYPE_ID, NAME, DESCRIPTION, COST, ITEM_COUNT, ACTIVE, CREATED_DATE, MODIFIED_DATE) VALUES ((SELECT ID FROM TYPE WHERE NAME = 'Jeans'), 'SlimFit Jeans', 'Jeans', 25.05, 60, 1, NOW(), null);
